// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdHaoPzFqGRiEsoaBrgimbv5W71AgTVDQ',
    appId: '1:874141957516:web:6ca9c966a693527af6aaa9',
    messagingSenderId: '874141957516',
    projectId: 'gaurav-portfolio-639a7',
    authDomain: 'gaurav-portfolio-639a7.firebaseapp.com',
    storageBucket: 'gaurav-portfolio-639a7.firebasestorage.app',
    measurementId: 'G-3VW0ZTTG54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb37m4OP5TgrOOtPoycbP1Qhgqd3DkN0E',
    appId: '1:874141957516:android:c58a9136a44b386df6aaa9',
    messagingSenderId: '874141957516',
    projectId: 'gaurav-portfolio-639a7',
    storageBucket: 'gaurav-portfolio-639a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv4UNEl-WPFx4Ui2SbRCa9qF4QYtHkPfE',
    appId: '1:874141957516:ios:1d4b472d7d1db414f6aaa9',
    messagingSenderId: '874141957516',
    projectId: 'gaurav-portfolio-639a7',
    storageBucket: 'gaurav-portfolio-639a7.firebasestorage.app',
    iosBundleId: 'com.gaurav.gauravPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv4UNEl-WPFx4Ui2SbRCa9qF4QYtHkPfE',
    appId: '1:874141957516:ios:1d4b472d7d1db414f6aaa9',
    messagingSenderId: '874141957516',
    projectId: 'gaurav-portfolio-639a7',
    storageBucket: 'gaurav-portfolio-639a7.firebasestorage.app',
    iosBundleId: 'com.gaurav.gauravPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdHaoPzFqGRiEsoaBrgimbv5W71AgTVDQ',
    appId: '1:874141957516:web:39ac0097820d552ef6aaa9',
    messagingSenderId: '874141957516',
    projectId: 'gaurav-portfolio-639a7',
    authDomain: 'gaurav-portfolio-639a7.firebaseapp.com',
    storageBucket: 'gaurav-portfolio-639a7.firebasestorage.app',
    measurementId: 'G-4G2KJBB6LC',
  );
}
